src/components/JobFilter.jsx
src/components/JobItem.jsx

fixed the fact that images on the vacature page exceed their border

Last enhancement

---

src/components/ContentfulPage.jsx

Cards around the contentful pages are now all removed

Remove all page cards

---

src/components/activities/ActivitiesWidget.jsx
src/components/activities/Activity.jsx

Lets check that this fix works on multiple machines before merging it.

fix stretched activity-images

---

src/components/layout/Footer.jsx
src/components/layout/GridDryQueries.jsx
src/components/layout/Layout.jsx
src/components/layout/MobileNavbar.jsx
src/components/layout/Navbar.jsx
src/data/Devices.jsx
src/pages/index.jsx

Also removed the dependency as it is no longer needed...

Remove React-responsive mediaqueries in favor of regular CSS

---

src/components/Drinks.jsx
src/components/News.jsx
src/components/activities/Activity.jsx
src/components/activities/ActivityWidget.jsx
src/components/jobs/FeaturedJobs.jsx
src/components/jobs/JobItem.jsx
src/components/jobs/JobsList.jsx
src/components/layout/ContentfulPage.jsx
src/components/layout/GridDryQueries.jsx
src/components/layout/Layout.jsx
src/components/layout/MobileNavbar.jsx
src/components/layout/Navbar.jsx
src/data/menu.json
src/helpers/ImageContainer.jsx
src/pages/carriere/partners.jsx
src/pages/carriere/vacatures.jsx
src/pages/index.jsx
src/pages/vereniging/activiteiten.jsx
src/pages/vereniging/besturen.jsx
src/pages/vereniging/disputen.jsx
src/semantic/src/site/views/card.variables
src/templates/JobTemplate.jsx
src/templates/NewsTemplate.jsx
src/templates/PartnerTemplate.jsx

This PR fixes most of current styling issues.

Fix all the stylings

---

src/components/Board.jsx
src/components/ContactPerson.jsx
src/pages/vereniging/besturen.jsx
src/templates/BoardTemplate.jsx

style board pages, replace hrefs with Link, add mobile version

Board styling

---

package-lock.json
package.json
src/components/Banner.jsx
src/components/Board.jsx
src/components/ContactPerson.jsx
src/components/News.jsx
src/components/activities/Activity.jsx
src/components/activities/ActivityWidget.jsx
src/components/layout/Navbar.jsx
src/templates/BoardTemplate.jsx
src/templates/DisputeTemplate.jsx

Adjust Activity to new Koala API

---

package-lock.json
src/components/News.jsx
src/templates/NewsTemplate.jsx

Add date of publishing to news items

---

src/components/layout/Navbar.jsx
src/data/menu.json

Knop foto's veranderd naar sign up en in dropdownmenu onder links de link foto's toegevoegd.

Knop aangepast en link naar menu verplaatst

---

src/data/menu.json

Added execute to the nav-bar

---

src/components/Mailchimp.jsx
src/components/layout/GridDryQueries.jsx
src/pages/index.jsx

I don't like the placement on the page, but apart from that this is a fully working signup form

Mailchimp signup form added

---

package-lock.json
package.json
src/components/Mailchimp.jsx
src/components/layout/GridDryQueries.jsx
src/components/layout/MobileNavbar.jsx
src/components/layout/Navbar.jsx
src/data/menu.json
src/pages/index.jsx
src/pages/vereniging/mailchimp.jsx

features include: website color automatically changes to board color, added sign-up button on frontpage, added link to GitHub

merge latest changes on development to master

---

src/templates/CommitteeTemplate.jsx
src/templates/DisputeTemplate.jsx

In committeeTemplate i used the grid from disputeTemplate so that the emailaddres is below the image.  In disputeTemplate i changed some small formatting stuff like image size and header size. Needs some testing.

WIP: Committee and dispute pages formatting

---

src/components/News.jsx
src/components/layout/Navbar.jsx
src/data/en-us.json
src/data/nl.json
src/templates/BoardTemplate.jsx

Fixed language switcher

---

src/components/layout/Navbar.jsx

use ordering from contentful for the navbar

---

src/components/jobs/JobFilter.jsx

changed the order in study filter on the vacancy page. Now "informatica" and "informatiekunde" are on the top of the list.

study order in study filter

---

README.md
package-lock.json
package.json
src/semantic/src/site/globals/site.variables

- Upgraded packages
- Updated README
- Board color change

2.6.1 Release

---

src/components/activities/Activity.jsx
src/data/en-us.json
src/data/nl.json

I don't know if there should also be a new translation for the english version. Right now it has the same translation, but without the exclamation mark. If this needs to change please make an issue

Created translation for sign up button on activity page

---

src/components/Drinks.jsx

Contentful now has a translation for the day. the code has been updated to deal with this.

Drinks day is now translated

---

src/components/layout/Navbar.jsx
src/data/menu.json

Was fixed by adding the language to the menu.json file. This is NOT the best solution. I've done this because the rendering of these objects is a bit weird and needs a proper refactor before it is able to be moved to contenful. A new issue has been created #274 for this refactor.

added translations to menu.json

---

src/components/TurnReveal.jsx
src/components/activities/Activity.jsx

Fix turnreveal flipping out of container

---

.github/workflows/build.yml

Fix scheduled CI runs by providing the worklflow attribute

---

src/components/jobs/FeaturedJobWidget.jsx
src/data/en-us.json
src/data/nl.json

Add button to vacancies under the featured vacancy

---

src/data/en-us.json
src/data/nl.json
src/static-pages/vereniging/contact.jsx

[add] added new mailto general mail address

---

src/semantic/src/site/globals/site.variables

Be beautiful again (Update color to B19)

---

src/templates/PageTemplate.jsx

fix: image alignment on samenwerking page

---

src/components/layout/Footer.jsx

As per the request of the current Extern, Jonathan Baumann, the facebook logo should be removed from the footer.
plz review, Kusjes!

removed facebook from the footer

---

src/static-pages/vereniging/huisstijl.jsx

Remove filled images
